IEEE_ETITC/IEEE_ETITC/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path( '', include( ('bases.urls', 'bases'), namespace='bases' ) ),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IEEE_ETITC/bases/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from bases.views import Home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path( '', Home.as_view(), name='home' ),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),
        name='login'),
    path('recuperar/',auth_views.LoginView.as_view(template_name='bases/recuperar.html'),
    name='recuperar'),
    path( 'logout/',
        auth_views.LogoutView.as_view( template_name='bases/home.html' ),
        name='logout' ),
        path('construccion/',auth_views.LoginView.as_view(template_name='bases/construccion.html'),
    name='construccion'),
    path('detalle/',auth_views.LoginView.as_view(template_name='bases/detalle.html'),
    name='detalle'),
]

IEEE_ETITC/miembro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from bases.views import Home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('miembro_detalle/',auth_views.LoginView.as_view(template_name='miembro/miembro_detalle.html'),
    name='miembro_detalle'),
    path('miembro_listar/',auth_views.LoginView.as_view(template_name='miembro/miembro_listar.html'),
    name='miembro_listar'),
]

IEEE_ETITC/miembro/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from bases.models import ClaseModelo
# Create your models here.

class Genero( ClaseModelo ):

    descripcion = models.CharField(
        max_length=45,
        help_text='Descripción del género',
        unique=True,
        verbose_name='Descripción género'
    )

    def __str__(self):
        return '{}'.format( self.descripcion )

    def save(self):
        self.descripcion = self.descripcion.upper()
        super( Genero, self ).save()

    class Meta:
        verbose_name = 'Género'
        verbose_name_plural = 'Géneros'

class Eps( ClaseModelo ):

    descripcion = models.CharField(
        max_length=45,
        help_text='Descripción de la EPS',
        unique=True,
        verbose_name='Descripción EPS'
    )

    def __str__(self):
        return '{}'.format( self.descripcion )

    def save(self):
        self.descripcion = self.descripcion.upper()
        super( Eps, self ).save()

    class Meta:
        verbose_name = 'EPS'
        verbose_name_plural = "EPS's"

class Ciudad( ClaseModelo ):

    descripcion = models.CharField(
        max_length=45,
        help_text='Descripción de la ciudad',
        unique=True,
        verbose_name='Descripción ciudad'
    )

    def __str__(self):
        return '{}'.format( self.descripcion )

    def save(self):
        self.descripcion = self.descripcion.upper()
        super( Ciudad, self ).save()

    class Meta:
        verbose_name = 'Ciudad'
        verbose_name_plural = "Ciudades"

class Barrio( ClaseModelo ):

    descripcion = models.CharField(
        max_length=45,
        help_text='Descripción del barrio',
        unique=True,
        verbose_name='Descripción barrio'
    )

    ciudad = models.ForeignKey(Ciudad, on_delete=models.PROTECT)

    nota = models.TextField(blank=True)

    def __str__(self):
        return '{}'.format( self.descripcion )

    def save(self):
        self.descripcion = self.descripcion.upper()
        super( Barrio, self ).save()

    class Meta:
        verbose_name = 'Barrio'
        verbose_name_plural = "Barrios"

class Tipo_sangre( ClaseModelo ):

    descripcion = models.CharField(
        max_length=45,
        help_text='Descripción del tipo de sangre',
        unique=True,
        verbose_name='Descripción tipo de sangre'
    )

    def __str__(self):
        return '{}'.format( self.descripcion )

    def save(self):
        self.descripcion = self.descripcion.upper()
        super( Tipo_sangre, self ).save()

    class Meta:
        verbose_name = 'Tipo_sangre'
        verbose_name_plural = "Tipo_sangre"

class Sede( ClaseModelo ):

    descripcion = models.CharField(
        max_length=255,
        help_text='Descripción de la sede dende estudia',
        unique=True,
        verbose_name='Descripción sede'
    )

    def __str__(self):
        return '{}'.format( self.descripcion )

    def save(self):
        self.descripcion = self.descripcion.upper()
        super( Sede, self ).save()

    class Meta:
        verbose_name = 'Sede'
        verbose_name_plural = 'Sedes'

class Rol_miembro( ClaseModelo ):

    descripcion = models.CharField(
        max_length=45,
        help_text='Descripción de la sede dende estudia',
        unique=True,
        verbose_name='Descripción sede'
    )

    def __str__(self):
        return '{}'.format( self.descripcion )

    def save(self):
        self.descripcion = self.descripcion.upper()
        super( Rol_miembro, self ).save()

    class Meta:
        verbose_name = 'Rol miembro'
        verbose_name_plural = 'Rol miembro'

class Miembro(AbstractUser, ClaseModelo):
    fecha_nacimiento = models.DateField(null=True)
    
    celular = models.CharField(max_length=15, null=True)
    
    genero = models.ForeignKey(Genero,
    help_text='Gérero del miembro',
    verbose_name='Género',
    on_delete=models.PROTECT,
    null=True
    )
    
    eps = models.ForeignKey(Eps,
    help_text='EPS del miembro',
    verbose_name='EPS',
    on_delete=models.PROTECT,
    null=True
    )

    barrio = models.ForeignKey(Barrio,
    help_text='Barrio donde vive el miembro',
    verbose_name='Barrio',
    on_delete=models.PROTECT,
    null=True
    )

    tipo_sangre = models.ForeignKey(Tipo_sangre,
    help_text='Tipo de sangre del miembro',
    verbose_name='RH',
    on_delete=models.PROTECT,
    null=True
    )

    sede = models.ForeignKey(Sede,
    help_text='Sede donde estudia el miembro',
    verbose_name='Sede',
    on_delete=models.PROTECT,
    null=True
    )

    rol_miembro = models.ForeignKey(Rol_miembro,
    help_text='Rol del miembro dentro de la rama',
    verbose_name='Rol miembro',
    on_delete=models.PROTECT,
    null=True
    )
    def __str__(self):
        return '{}'.format( self.first_name + " " + self.last_name )

    class Meta:
        verbose_name = 'Miembro'
        verbose_name_plural = 'Miembros'

IEEE_ETITC/miembro/forms.py
from django import forms
from django.db import *

from .models import *
from django.contrib.auth.models import User



class MiembroForm( forms.ModelForm ):

    class Meta:
        model = Miembro
        fields = ['username', 'first_name', 'last_name',
                  'email', 'sede', 'rol_miembro']
        labels = {'username': 'Correo institucional'}
        widget = {'username': forms.EmailInput,
                  }

    def __init__(self, *args, **kwargs):
        super().__init__( *args, **kwargs )
        for field in iter( self.fields ):
            self.fields[field].widget.attrs.update( {
                'class': 'form-control'
            } )

IEEE_ETITC/miembro/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render, redirect


from .models import *
from .forms import *

class MiembroView(generic.ListView):
    model = Miembro
    template_name = 'miembro/miembro_listar.html'
    context_object_name = 'obj'

IEEE_ETITC/miembro/templates/miembro/miembro_detalle.html
{% extends 'base/base.html' %}
{% block miembros %}<strong>Miembros</strong>{% endblock %}
{% block page_content%}

  <div class="wrapper">
   	<nav id="sidebar">
   		<div class="sidebar-header">
   			<h3>Miembro</h3>
   		</div>
   		
   		
   		<ul class="list-unstyled components">
   		
				{% if user.is_superuser %}
        <li>
					<a href="{{BASE_DIR}}/admin/miembro/miembro/add/">Crear</a>
				</li>
   		  {% endif %}
   			{% if user.is_superuser %}
				<li>
					<a href="{{BASE_DIR}}/admin/miembro/miembro/">Listar</a>
				</li>
			{%else %}

				<li>
					<a href="{% url 'miembro:miembro_listar' %}">Listar</a>
				</li>
			{%endif%}
				<li>
					<a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Filtar</a>
					<ul class="collapse list-unstyled" id="pageSubmenu">
						<li>
							<a href="#">Nombre</a>
						</li>
						<li>
							<a href="#">Carrera</a>
						</li>
						<li>
							<a href="#">Capitulo</a>
						</li>
					</ul> 
				</li>
			   
				<li>
   				<a href="#">Puntos</a>
				</li>
   		</ul>
   	</nav>
   	
   	<div class="content">
   		<nav class="navbar navbar-expand-lg navbar-light bg-light">
   		
   		
   		
</nav>


  	 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  	
  	<div class="line"></div>
  	<h2>Collapsible Sidebar Using Bootstrap 4</h2>
  	
  	
  	<div class="line"></div>
  	
   	</div>
   	
   	
   	
   	
   	
   </div>
    

    


{% endblock %}

IEEE_ETITC/miembro/templates/miembro/miembro_form.html
{% extends 'base/base.html' %}
{% block usuario %}
{% endblock%}
{% block page_content %}
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <small class="text-danger">
                        {% if form.errors %}
                            {% for field in form %}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        {{ error|escape }}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        
                            {% if form.non_field_errors%}
                                {% for error in form.non_field_errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            {% endif %}
                        {% endif %}
                    </small>
                  </div>
                  <form class="user" method="POST">
                    {% csrf_token %}
                    

                    { { form.as_p } from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic


class Home( generic.TemplateView ):
    template_name = 'bases/home.html'
    login_url='bases:login'}

                    <button type="submit" class="btn btn-primary btn-user btn-block">Iniciar sesión</button>
                    <a  class="nav-link btn " href="{% url 'bases:recuperar' %}">Olvidé mi contraseña</a>
                </div>
              </div>

      </div>

    </div>

  </div>

</div>
{% endblock %}

IEEE_ETITC/miembro/templates/miembro/miembro_listar.html
{% extends 'base/base.html' %}
{% block miembros %}<strong>Miembros</strong>{% endblock %}
{% block page_content%}

  <div class="wrapper">
   	<nav id="sidebar">
   		<div class="sidebar-header">
   			<h3>Miembro</h3>
   		</div>
   		
   		
   		<ul class="list-unstyled components">
   		
				{% if user.is_superuser %}
        <li>
					<a href="{{BASE_DIR}}/admin/miembro/miembro/add/">Crear</a>
				</li>
   		  {% endif %}
   			{% if user.is_superuser %}
				<li>
					<a href="{{BASE_DIR}}/admin/miembro/miembro/">Listar</a>
				</li>
			{%else %}

				<li>
					<a href="#">Listar</a>
				</li>
			{%endif%}
				<li>
					<a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Filtar</a>
					<ul class="collapse list-unstyled" id="pageSubmenu">
						<li>
							<a href="#">Nombre</a>
						</li>
						<li>
							<a href="#">Carrera</a>
						</li>
						<li>
							<a href="#">Capitulo</a>
						</li>
					</ul> 
				</li>
			   
				<li>
   				<a href="#">Puntos</a>
				</li>
   			</ul>
   		</nav>
   	
   		<div class="content">
   		<nav class="navbar navbar-expand-lg navbar-light bg-light">
	</nav>

	<div class='container'>
		<div class='col-12'>
			<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de miembros</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">Usted no cuenta con los permisos necesarios para ver los miembros, necesita iniciar sesión.</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
            <!--<th>RFID</th>-->
            <th>username</th>
            <th>Doc.</th>
            <th>N. doc.</th>
            <th>Dependencia</th>
            <th>Tipo</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>E-mail</th>
            <th>F. Nac</th>
            <th>Saldo</th>
            <!--<<th>F. Creado</th>
            <th>F. Modif.</th>
            <th>Foto</th>-->
            <th class="all">Acciones</th>
            </thead>
            <tbody>
            {% for item in obj %}
            <tr>
                <!--<<td>{{ item.id_beneficiario }}</td>-->
                <td>{{ item.username }}</td>
                <td>{{ item.documento|title }}</td>
                <td>{{ item.numero_documento }}</td>
                <td>{{ item.dependencia|title }}</td>
                <td>{{ item.tipo_beneficiario|title }}</td>
                <td>{{ item.nombres|title }}</td>
                <td>{{ item.apellidos|title }}</td>
                
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Registros por página: _MENU_",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });


</script>
		</div>
	</div>
   	
   	
   	
   </div>
    

    <script>
	    $(document).ready(function(){
			$('#sidebarCollapse').on('click',function(){
				$('#sidebar').toggleClass('active');
			});
		});  
	</script>


{% endblock %}