IEEE_ETITC/IEEE_ETITC/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path( '', include( ('bases.urls', 'bases'), namespace='bases' ) ),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IEEE_ETITC/bases/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from bases.views import Home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path( '', Home.as_view(), name='home' ),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),
        name='login'),
    path('recuperar/',auth_views.LoginView.as_view(template_name='bases/recuperar.html'),
    name='recuperar'),
    path( 'logout/',
        auth_views.LogoutView.as_view( template_name='bases/home.html' ),
        name='logout' ),
        path('construccion/',auth_views.LoginView.as_view(template_name='bases/construccion.html'),
    name='construccion'),
    path('detalle/',auth_views.LoginView.as_view(template_name='bases/detalle.html'),
    name='detalle'),
]

IEEE_ETITC/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IEEE-ETITC</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="icon" href="https://serv2.raiolanetworks.es/favicon-navegadores.png" sizes="32x32" type="image/png">
    <link href="{% static  'base/css/sb-admin-2.min.css' %}" rel="stylesheet">

<body>
<div class='container-fluid'>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <img src="{% static 'base/img/Rama.png' %}" style="width: 60px; height: 40px;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">

            <li class="nav-item">
              <a class="nav-link" href="{% url 'bases:home' %}">{% block inicio %}Inicio{% endblock %}</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'miembro:miembro_detalle' %}">{% block miembros %}Miembros{% endblock %}</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'bases:construccion' %}">{% block actividades %}Actividades{% endblock %}</a>
              </li>

            <li class="nav-item">
            <a class="nav-link" href="{% url 'bases:construccion' %}">{% block organigrama %}Organigrama{% endblock %}</a>
            </li>

            <li class="nav-item">
            <a class="nav-link" href="{% url 'bases:construccion' %}">{% block capitulos %}Capítulos técnicos{% endblock %}</a>
            </li>

            <li class="nav-item">
            <a class="nav-link" href="{% url 'bases:construccion' %}">{% block hoja %}Hoja de vida{% endblock %}</a>
            </li>

            <li class="nav-item">
            <a class="nav-link" href="{% url 'bases:construccion' %}">{% block beneficios %}Beneficios{% endblock %}</a>
            </li>
  
            <li class="nav-item">
            <a class="nav-link" href="{% url 'bases:construccion' %}">{% block contacto %}Contacto{% endblock %}</a>
            </li>

            
            
            {% block usuario %} 
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="http://127.0.0.1:8000/admin/logout/" role="button" aria-haspopup="true" aria-expanded="false"><strong>{{ user.username.title|lower }}</strong></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="http://127.0.0.1:8000/admin/miembro/miembro/{{user.id}}/change/">Perfil</a>
                  <a class="dropdown-item" href="{% url 'bases:logout' %}">Salir</a>
                </div>
              </li> 
              {% else %}
              <a  class="nav-link btn btn-secondary" href="{% url 'bases:login' %}">Iniciar sesión</a>
              {% endif %}

                {% endblock %}</a> 
            </li>
          </ul>
        </div>
      </nav>

      {% block page_content %}
      <div class="container-fluid">

        <!-- Page Heading -->
       

      </div>
      {% endblock %}

      <!-- Footer -->
      <footer class="footer fixed-bottom bg-secondary ">
      
        
      <div class="text-center">© Todos los derechos reservados. 2020 Rama Estudiantil IEEE-ETITC</div>
    </footer>


    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">¿Listo para salir?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Seleccione "Cerrar sesión" a continuación si está listo para finalizar su sesión
                    actual.
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" href="{% url 'bases:logout' %}">Cerrar sesión</a>
                </div>
            </div>
        </div>
    </div>


<div class="modal fade" id="popup"></div>


<!-- Footer -->
      <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
      </div>
</body>
</html>